In [23]:
from keras.datasets import imdb
import numpy as np
(train_data,train_target),(test_data,test_target)=imdb.load_data(num_words=10000)

In [24]:
def vectorize(sequences, dimension=10000):
    results = np.zeros((len(sequences),dimension))
    for i, seq in enumerate(sequences):
        results[i,seq]=1
    return results

In [25]:
x_train=vectorize(train_data)
x_test=vectorize(test_data)

In [26]:
y_train=np.array(train_target,dtype='float32')
y_test=np.array(test_target,dtype='float32')

In [27]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from keras.losses import binary_crossentropy

In [32]:
model=Sequential()
model.add(Dense(16,activation="relu", input_shape=(10000,)))
model.add(Dense(8,activation="relu"))
model.add(Dense(1,activation="sigmoid"))


In [34]:
model.compile(optimizer='adam',loss='binary_crossentropy', metrics='accuracy')

In [37]:
model.fit(x_train,
    y_train,
    batch_size=8,
    epochs=20,
    validation_data=(x_test,y_test))

Epoch 1/20
3125/3125 [==============================] - 10s 3ms/step - loss: 0.0060 - accuracy: 0.9985 - val_loss: 1.2872 - val_accuracy: 0.8463
Epoch 2/20
3125/3125 [==============================] - 9s 3ms/step - loss: 0.0026 - accuracy: 0.9993 - val_loss: 1.4857 - val_accuracy: 0.8516
Epoch 3/20
3125/3125 [==============================] - 9s 3ms/step - loss: 0.0020 - accuracy: 0.9994 - val_loss: 1.5374 - val_accuracy: 0.8553
Epoch 4/20
3125/3125 [==============================] - 9s 3ms/step - loss: 0.0024 - accuracy: 0.9994 - val_loss: 1.5685 - val_accuracy: 0.8558
Epoch 5/20
3125/3125 [==============================] - 9s 3ms/step - loss: 0.0021 - accuracy: 0.9994 - val_loss: 1.5953 - val_accuracy: 0.8417
Epoch 6/20
3125/3125 [==============================] - 9s 3ms/step - loss: 0.0014 - accuracy: 0.9995 - val_loss: 1.6570 - val_accuracy: 0.8562
Epoch 7/20
3125/3125 [==============================] - 10s 3ms/step - loss: 9.0443e-04 - accuracy: 0.9997 - val_loss: 1.6790 - val_acc

In [38]:
model.evaluate(x_test,y_test)

782/782 [==============================] - 1s 1ms/step - loss: 3.0529 - accuracy: 0.8567


[3.0528528690338135, 0.8566799759864807]

In [39]:
result={0:"Negative",1:"Positive"}

In [40]:
test_data[0]

[1,
 591,
 202,
 14,
 31,
 6,
 717,
 10,
 10,
 2,
 2,
 5,
 4,
 360,
 7,
 4,
 177,
 5760,
 394,
 354,
 4,
 123,
 9,
 1035,
 1035,
 1035,
 10,
 10,
 13,
 92,
 124,
 89,
 488,
 7944,
 100,
 28,
 1668,
 14,
 31,
 23,
 27,
 7479,
 29,
 220,
 468,
 8,
 124,
 14,
 286,
 170,
 8,
 157,
 46,
 5,
 27,
 239,
 16,
 179,
 2,
 38,
 32,
 25,
 7944,
 451,
 202,
 14,
 6,
 717]

In [41]:
d=vectorize(test_data)

In [42]:
d

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [43]:
d[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [44]:
d[0][0]

0.0

In [45]:
l=model.predict(d)

782/782 [==============================] - 2s 2ms/step


In [46]:
l

array([[9.9514024e-09],
       [1.0000000e+00],
       [1.0000000e+00],
       ...,
       [2.3059762e-12],
       [2.6160501e-16],
       [9.9112934e-01]], dtype=float32)

In [47]:
l[0]

array([9.951402e-09], dtype=float32)

In [48]:
l[0][0]

9.951402e-09

In [49]:
if l[0][0] < 0.5:
    l=0
else:
    l=1

In [50]:
print(result[l])

Negative


In [53]:
print(result[test_target[0]])

Negative
